version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12.12
    hostname: rabbitmq
    restart: always
    env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}]
    ports:
      - 15672:15672
      - 5672:5672
